use rust_decimal::Decimal;
use crate::asteroid_mining::{Field,AsteroidMiningData,AsteroidMineToken};

use crate::common::GoodConsumes;

grammar;

extern {
    type Location = usize;
    type Error = String;

    enum AsteroidMineToken{
        "string" => AsteroidMineToken::String(<String>),
        "number" => AsteroidMineToken::Number(<u8>),
        "decimal_number" => AsteroidMineToken::DecimalNumber(<Decimal>),

        "=" => AsteroidMineToken::Equal,
        ":" => AsteroidMineToken::Colon,

        "{" => AsteroidMineToken::LeftCurly,
        "}" => AsteroidMineToken::RightCurly,

        "[" => AsteroidMineToken::LeftSquare,
        "]" => AsteroidMineToken::RightSquare,

        "name" => AsteroidMineToken::Name,
        "depot_asset" => AsteroidMineToken::DepotAsset,
        "ship_asset" => AsteroidMineToken::ShipAsset,

        "good_id" => AsteroidMineToken::GoodId,

        "amount" => AsteroidMineToken::Amount,

        "consumes" => AsteroidMineToken::Consumes,
        "produces" => AsteroidMineToken::Produces,

        "power" => AsteroidMineToken::Power,

        "time" => AsteroidMineToken::Time,

    }
}

pub AsteroidMiningData:Vec<AsteroidMiningData> = {
    <list:AsteroidMiningDatum*> => list,
}

AsteroidMiningDatum:AsteroidMiningData = {
    <level:"number"> "=" "{" <fields:AsteroidField*>  "}" => {
        let mut asteroid_mine = AsteroidMiningData{
            level,
            ..Default::default()
        };

        for f in fields {
            match f {
                Field::Name(n) => asteroid_mine.name = n,
                Field::DepotAsset(n) => asteroid_mine.depot_asset = n,
                Field::ShipAsset(n) => asteroid_mine.ship_asset = n,
                Field::Consumes(c) => asteroid_mine.costs = c,
                Field::Produces(c) => asteroid_mine.produces = c,
                Field::Time(t) => asteroid_mine.time = t,
                Field::Power(p) => asteroid_mine.power = p,
            }
        }
        asteroid_mine
    }
}

AsteroidField:Field ={
    <n:Name> => Field::Name(n),
    <a:DepotAsset> => Field::DepotAsset(a),
    <a:ShipAsset> => Field::ShipAsset(a),
    <c:GoodConsumes> => Field::Consumes(c),
    <c:GoodProduces> => Field::Produces(c),
    <t:Time> => Field::Time(t),
    <p:Power> => Field::Power(p),
}

Name:String = {
    "name" "=" <s:"string"> => s,
}

DepotAsset:String = {
    "depot_asset" "=" <s:"string"> =>s,
}

ShipAsset:String = {
    "ship_asset" "=" <s:"string"> =>s,
}

Time:u8 = {
    "time" "=" <t:"number"> => t,
}

Power:Decimal = {
    "power" "=" <p:"decimal_number"> => p,
}

GoodProduces:Vec<GoodConsumes> = {
    "produces" "=" "[" <c:GoodConsume*> "]" =>c,
}
GoodConsumes:Vec<GoodConsumes> = {
    "consumes" "=" "[" <c:GoodConsume*> "]" =>c,
}

GoodConsume:GoodConsumes = {
    "{" "good_id" ":" <id:"string"> "amount" ":" <n:"decimal_number"> "}" => {
        GoodConsumes {
            id,
            amount:n,
        }
    }
}
