use crate::star::{StarData,StarField,StarToken};

use rust_decimal::prelude::*;

grammar;

extern {
    type Location = usize;
    type Error = String;

    enum StarToken {
        "string" => StarToken::String(<String>),
        "decimal_number" => StarToken::DecimalNumber(<Decimal>),

        "=" => StarToken::Equal,
        "{" => StarToken::LeftCurly,
        "}" => StarToken::RightCurly,


        "asset_location" => StarToken::AssetLocation,
        "scale" => StarToken::Scale,

        "click_sound" => StarToken::ClickSound,

    }
}

pub StarData:Vec<StarData> = {
    StarDatum*
}

StarDatum:StarData = {
    <id:"string"> "=" "{" <fields:StarField*> "}" => {
        let mut star_data = StarData{
            id,
            ..Default::default()
        };
        for f in fields {
            match f {
                StarField::AssetLocation(a) => star_data.asset_location = a,
                StarField::Scale(s) => star_data.scale = s,
                StarField::ClickLocation(c) => star_data.click_location = c,
            }
        }
        star_data
    }

}

StarField:StarField = {
    <a:AssetLocation> => StarField::AssetLocation(a),
    <s:Scale> => StarField::Scale(s),
    <c:ClickLocation> => StarField::ClickLocation(c),
}

AssetLocation:String = {
    "asset_location" "=" <s:"string"> => s,
}

Scale:Decimal = {
    "scale" "=" <n:"decimal_number"> => n,
}

ClickLocation:String = {
    "click_sound" "=" <id:"string"> => id.to_string()
}
